const mongoose = require('mongoose');
const Task = require('../models/Task');
const memoryStore = require('../services/memoryStore');
const { emitTaskUpdate } = require('../services/socketService');

// @desc    Get staff clinical tasks
// @route   GET /api/tasks
const getTasks = async (req, res, next) => {
  try {
    const { status, priority, patientId, mineOnly } = req.query;

    if (mongoose.connection.readyState === 1) {
      const query = {};
      if (status) query.status = status;
      if (priority) query.priority = priority;
      if (patientId) query.patient = patientId;

      if (mineOnly === 'true' && req.user) {
        query.assignedTo = req.user._id || req.user.id;
      }

      const tasks = await Task.find(query)
        .populate('assignedTo', 'name email role department')
        .populate('patient', 'fullName mrn triagePriority currentBed')
        .populate('bed', 'bedNumber ward')
        .sort({ createdAt: -1 });

      return res.json({ success: true, count: tasks.length, tasks });
    } else {
      // Memory Store
      let tasks = [...memoryStore.tasks];
      if (status && status !== 'ALL') tasks = tasks.filter((t) => t.status === status);
      if (priority) tasks = tasks.filter((t) => t.priority === priority);
      if (patientId) tasks = tasks.filter((t) => (t.patient?._id || t.patient) === patientId);

      if (mineOnly === 'true' && req.user) {
        const userId = req.user._id || req.user.id;
        tasks = tasks.filter((t) => (t.assignedTo?._id || t.assignedTo) === userId);
      }

      return res.json({ success: true, count: tasks.length, tasks });
    }
  } catch (error) {
    next(error);
  }
};

// @desc    Create a new manual clinical task
// @route   POST /api/tasks
const createTask = async (req, res, next) => {
  try {
    const { title, description, priority, assignedTo, patientId, bedId, category } = req.body;

    if (mongoose.connection.readyState === 1) {
      const task = await Task.create({
        title,
        description,
        priority: priority || 'MEDIUM',
        assignedTo: assignedTo || req.user?._id,
        patient: patientId,
        bed: bedId || null,
        category: category || 'Nursing Care',
        autoGeneratedByAI: false,
      });

      const populatedTask = await Task.findById(task._id)
        .populate('assignedTo', 'name role')
        .populate('patient', 'fullName mrn');

      emitTaskUpdate(populatedTask);
      return res.status(201).json({ success: true, message: 'Clinical task created', task: populatedTask });
    } else {
      // Memory Store
      const patient = memoryStore.patients.find((p) => p._id === patientId);
      const staff = memoryStore.users.find((u) => u._id === assignedTo) || req.user;

      const newTask = {
        _id: `task-${Date.now()}`,
        title,
        description,
        priority: priority || 'MEDIUM',
        assignedTo: staff,
        patient,
        bed: bedId ? memoryStore.beds.find((b) => b._id === bedId) : null,
        category: category || 'Nursing Care',
        status: 'pending',
        autoGeneratedByAI: false,
        createdAt: new Date(),
      };

      memoryStore.tasks.unshift(newTask);
      emitTaskUpdate(newTask);
      return res.status(201).json({ success: true, message: 'Clinical task created', task: newTask });
    }
  } catch (error) {
    next(error);
  }
};

// @desc    Update task execution status (pending, in_progress, completed)
// @route   PATCH /api/tasks/:id/status
const updateTaskStatus = async (req, res, next) => {
  try {
    const { status } = req.body;
    const id = req.params.id;

    if (mongoose.connection.readyState === 1) {
      const task = await Task.findById(id);
      if (!task) return res.status(404).json({ success: false, message: 'Task not found' });

      task.status = status;
      if (status === 'completed') {
        task.completedAt = new Date();
        task.completedBy = req.user?._id;
      }
      await task.save();

      const populatedTask = await Task.findById(task._id)
        .populate('assignedTo', 'name role')
        .populate('patient', 'fullName mrn');

      emitTaskUpdate(populatedTask);
      return res.json({ success: true, message: `Task updated to ${status}`, task: populatedTask });
    } else {
      // Memory Store
      const task = memoryStore.tasks.find((t) => t._id === id);
      if (!task) return res.status(404).json({ success: false, message: 'Task not found' });

      task.status = status;
      if (status === 'completed') {
        task.completedAt = new Date();
        task.completedBy = req.user;
      }

      emitTaskUpdate(task);
      return res.json({ success: true, message: `Task updated to ${status}`, task });
    }
  } catch (error) {
    next(error);
  }
};

module.exports = {
  getTasks,
  createTask,
  updateTaskStatus,
};
