const mongoose = require('mongoose');
const Patient = require('../models/Patient');
const TriageRecord = require('../models/TriageRecord');
const Task = require('../models/Task');
const memoryStore = require('../services/memoryStore');
const { evaluatePatientTriage } = require('../services/geminiService');
const { autoAssignStaffMember } = require('../services/resourceOptimizerService');
const { emitTriageUpdate, emitTaskUpdate } = require('../services/socketService');

// @desc    Run Google Gemini AI Triage evaluation & orchestrate clinical workflow
// @route   POST /api/triage/evaluate
const evaluateTriage = async (req, res, next) => {
  try {
    const { patientId, chiefComplaint, symptoms, nurseNotes, vitals } = req.body;

    let patient;
    if (mongoose.connection.readyState === 1) {
      patient = await Patient.findById(patientId);
    } else {
      patient = memoryStore.patients.find((p) => p._id === patientId);
    }

    if (!patient) {
      return res.status(404).json({ success: false, message: 'Patient record not found' });
    }

    // Call Gemini AI Triage Engine
    const aiEvaluation = await evaluatePatientTriage({
      patientName: patient.fullName,
      age: patient.age,
      gender: patient.gender,
      chiefComplaint,
      symptoms,
      vitals,
      nurseNotes,
    });

    const isAbnormal = aiEvaluation.severity === 'CRITICAL' || aiEvaluation.severity === 'URGENT';

    // Auto-assign staff
    let assignedStaff = patient.assignedDoctor || patient.assignedNurse;
    if (!assignedStaff) {
      assignedStaff = await autoAssignStaffMember(aiEvaluation.requiredStaffRole, aiEvaluation.recommendedWard);
    }

    const createdTasks = [];

    if (mongoose.connection.readyState === 1) {
      patient.triagePriority = aiEvaluation.severity;
      patient.esiScore = aiEvaluation.esiScore;
      patient.latestVitals = { ...vitals, isAbnormal, timestamp: new Date() };

      if (!patient.assignedDoctor && aiEvaluation.requiredStaffRole === 'doctor' && assignedStaff) {
        patient.assignedDoctor = assignedStaff._id;
      }
      if (!patient.assignedNurse && aiEvaluation.requiredStaffRole === 'nurse' && assignedStaff) {
        patient.assignedNurse = assignedStaff._id;
      }

      await patient.save();

      const triageRecord = await TriageRecord.create({
        patient: patient._id,
        intakeNurse: req.user?._id || null,
        chiefComplaint,
        symptoms: Array.isArray(symptoms) ? symptoms : [symptoms],
        rawNurseNotes: nurseNotes,
        vitalsSnapshot: vitals,
        aiSeverity: aiEvaluation.severity,
        esiScore: aiEvaluation.esiScore,
        recommendedWard: aiEvaluation.recommendedWard,
        clinicalRationale: aiEvaluation.clinicalRationale,
        immediateActions: aiEvaluation.immediateActions,
        requiredStaffRole: aiEvaluation.requiredStaffRole,
        assignedStaff: assignedStaff?._id || null,
        modelUsed: aiEvaluation.modelUsed,
        isFallback: aiEvaluation.isFallback,
      });

      if (assignedStaff && aiEvaluation.immediateActions) {
        for (const actionText of aiEvaluation.immediateActions.slice(0, 3)) {
          const task = await Task.create({
            title: actionText,
            description: `AI Orchestration: Recommended for ${patient.fullName} based on ESI ${aiEvaluation.esiScore}`,
            priority: aiEvaluation.severity === 'CRITICAL' ? 'CRITICAL' : 'HIGH',
            assignedTo: assignedStaff._id,
            patient: patient._id,
            bed: patient.currentBed,
            category: actionText.toLowerCase().includes('iv') ? 'Medication' : 'Physician Exam',
            autoGeneratedByAI: true,
          });
          createdTasks.push(task);
          emitTaskUpdate(task);
        }
      }

      emitTriageUpdate({
        triageRecord,
        patientId: patient._id,
        patientName: patient.fullName,
        priority: aiEvaluation.severity,
        esiScore: aiEvaluation.esiScore,
        recommendedWard: aiEvaluation.recommendedWard,
        createdTasks,
      });

      return res.status(200).json({
        success: true,
        message: 'AI Triage evaluation completed and workflow orchestrated.',
        evaluation: aiEvaluation,
        triageRecord,
        assignedStaff,
        autoGeneratedTasks: createdTasks,
      });
    } else {
      // Memory Store
      patient.triagePriority = aiEvaluation.severity;
      patient.esiScore = aiEvaluation.esiScore;
      patient.latestVitals = { ...vitals, isAbnormal, timestamp: new Date() };

      if (!patient.assignedDoctor && aiEvaluation.requiredStaffRole === 'doctor' && assignedStaff) {
        patient.assignedDoctor = assignedStaff;
      }
      if (!patient.assignedNurse && aiEvaluation.requiredStaffRole === 'nurse' && assignedStaff) {
        patient.assignedNurse = assignedStaff;
      }

      const triageRecord = {
        _id: `triage-${Date.now()}`,
        patient: { _id: patient._id, fullName: patient.fullName, mrn: patient.mrn },
        chiefComplaint,
        symptoms: Array.isArray(symptoms) ? symptoms : [symptoms],
        rawNurseNotes: nurseNotes,
        vitalsSnapshot: vitals,
        aiSeverity: aiEvaluation.severity,
        esiScore: aiEvaluation.esiScore,
        recommendedWard: aiEvaluation.recommendedWard,
        clinicalRationale: aiEvaluation.clinicalRationale,
        immediateActions: aiEvaluation.immediateActions,
        requiredStaffRole: aiEvaluation.requiredStaffRole,
        assignedStaff,
        modelUsed: aiEvaluation.modelUsed,
        isFallback: aiEvaluation.isFallback,
        createdAt: new Date(),
      };

      memoryStore.triageRecords.unshift(triageRecord);

      if (assignedStaff && aiEvaluation.immediateActions) {
        for (const actionText of aiEvaluation.immediateActions.slice(0, 3)) {
          const task = {
            _id: `task-${Date.now()}-${Math.random().toString(36).substr(2, 4)}`,
            title: actionText,
            description: `AI Orchestration: Recommended for ${patient.fullName} based on ESI ${aiEvaluation.esiScore}`,
            priority: aiEvaluation.severity === 'CRITICAL' ? 'CRITICAL' : 'HIGH',
            assignedTo: assignedStaff,
            patient,
            bed: patient.currentBed,
            category: actionText.toLowerCase().includes('iv') ? 'Medication' : 'Physician Exam',
            status: 'pending',
            autoGeneratedByAI: true,
            createdAt: new Date(),
          };
          createdTasks.push(task);
          memoryStore.tasks.unshift(task);
          emitTaskUpdate(task);
        }
      }

      emitTriageUpdate({
        triageRecord,
        patientId: patient._id,
        patientName: patient.fullName,
        priority: aiEvaluation.severity,
        esiScore: aiEvaluation.esiScore,
        recommendedWard: aiEvaluation.recommendedWard,
        createdTasks,
      });

      return res.status(200).json({
        success: true,
        message: 'AI Triage evaluation completed and workflow orchestrated.',
        evaluation: aiEvaluation,
        triageRecord,
        assignedStaff,
        autoGeneratedTasks: createdTasks,
      });
    }
  } catch (error) {
    next(error);
  }
};

// @desc    Get triage history across hospital
// @route   GET /api/triage/history
const getTriageHistory = async (req, res, next) => {
  try {
    if (mongoose.connection.readyState === 1) {
      const history = await TriageRecord.find()
        .populate('patient', 'fullName mrn age gender status')
        .populate('assignedStaff', 'name role department')
        .sort({ createdAt: -1 })
        .limit(50);
      return res.json({ success: true, count: history.length, history });
    } else {
      return res.json({ success: true, count: memoryStore.triageRecords.length, history: memoryStore.triageRecords });
    }
  } catch (error) {
    next(error);
  }
};

module.exports = {
  evaluateTriage,
  getTriageHistory,
};
